language: generic
sudo: false
services:
  - docker
matrix:
  include:
    - env:
      - CXX=g++
        DOC=dousu/docker_cpp_with_boost
      install:
        - docker pull $DOC
    - env:
      - CXX="clang++ -stdlib=libc++"
        DOC=dousu/docker_cpp_with_boost
      install:
        - docker pull $DOC
script:
  - docker run -w /tmp/MAILM -v $PWD:/tmp/MAILM -e CXX $DOC /bin/sh -c "$CXX -v && make -j test"
notifications:
  email:
    on_failure: change
    on_success: never
